In [4]:
%load_ext autoreload
%autoreload 2

%config Completer.use_jedi = False

import h5py, numpy as np

# Astrometry

In [25]:
data_box = {}

with h5py.File('/data/asfe2/Projects/astrometry/PyOutput/chisquare_astrometry_jmax5_nside64_M85_CGR1_lm0.3_B2.0_ncores88_scipy_results.h5', 'r') as hf:
    print(hf.keys())
    print(hf['x'].shape)
    for key in hf.keys():
        data_box[key] = hf[key][...]

<KeysViewHDF5 ['Clim', 'Mlim', 'b', 'lnP', 'opt_runtime', 'optimum_lnp_history', 'x', 'z']>
(85, 1, 49152)


In [26]:
data_box['Mlim'],data_box['Clim']

(array([ 5. , 21.9]), array([-100.,   99.]))

In [29]:
data_box['lengthscales'] = [0.3, 200]
data_box['B'] = 2.0
data_box['j'] = np.arange(6, dtype=int)
data_box['Mlim'] = [5.,22.]
data_box['Clim'] = [-100.,100.]

with h5py.File('/data/asfe2/Projects/testselectionfunctions/cog_vi/astrometry_cogvi.h5', 'w') as hf:
    for key in data_box.keys():
        hf.create_dataset(key, data=data_box[key])

In [30]:
data_box['Mlim'],data_box['Clim']

([5.0, 22.0], [-100.0, 100.0])

In [39]:
with h5py.File('/data/asfe2/Projects/testselectionfunctions/cog_vi/astrometry_cogvi.h5', 'r') as hf:
    print(float(hf['B'][...]))

2.0


# RVS

In [21]:
data_box = {}

with h5py.File('/data/asfe2/Projects/astrometry/PyOutput/chisquare_rvs_jmax5_nside64_M61_CGR4_lm0.3lc1.5_B2.0_ncores80_scipy_results.h5', 'r') as hf:
    print(hf.keys())
    print(hf['x'].shape)
    for key in hf.keys():
        data_box[key] = hf[key][...]

<KeysViewHDF5 ['Clim', 'Mlim', 'b', 'lnP', 'opt_runtime', 'optimum_lnp_history', 'x', 'z']>
(61, 4, 49152)


In [22]:
data_box['Mlim'],data_box['Clim']

(array([ 5. , 17.2]), array([-1.,  3.]))

In [11]:
data_box['lengthscales'] = [0.3, 1.5]
data_box['B'] = 2.0
data_box['j'] = np.arange(6, dtype=int)

with h5py.File('/data/asfe2/Projects/testselectionfunctions/cog_vi/rvs_cogvi.h5', 'w') as hf:
    for key in data_box.keys():
        hf.create_dataset(key, data=data_box[key])

# RUWE

In [16]:
data_box = {}

with h5py.File('/data/asfe2/Projects/astrometry/PyOutput/chisquare_ruwe1p4_jmax5_nside64_M85_CGR4_lm0.3lc3.0_B2.0_ncores88_scipy_results.h5', 'r') as hf:
    print(hf.keys())
    print(hf['x'].shape)
    for key in hf.keys():
        data_box[key] = hf[key][...]

<KeysViewHDF5 ['Clim', 'Mlim', 'b', 'lnP', 'opt_runtime', 'optimum_lnp_history', 'x', 'z']>
(85, 4, 49152)


In [18]:
data_box['Mlim'],data_box['Clim']

(array([ 5., 22.]), array([-1.,  7.]))

In [19]:
data_box['lengthscales'] = [0.3, 3.0]
data_box['B'] = 2.0
data_box['j'] = np.arange(6, dtype=int)

with h5py.File('/data/asfe2/Projects/testselectionfunctions/cog_vi/ruwe1p4_magcol_cogvi.h5', 'w') as hf:
    for key in data_box.keys():
        hf.create_dataset(key, data=data_box[key])

In [20]:
data_box['Mlim'],data_box['Clim']

(array([ 5., 22.]), array([-1.,  7.]))

In [14]:
data_box = {}

with h5py.File('/data/asfe2/Projects/astrometry/PyOutput/chisquare_ruwe1p4_jmax5_nside64_M85_CGR1_lm0.3lc200.0_B2.0_ncores88_scipy_results.h5', 'r') as hf:
    print(hf.keys())
    print(hf['x'].shape)
    for key in hf.keys():
        data_box[key] = hf[key][...]

<KeysViewHDF5 ['Clim', 'Mlim', 'b', 'lnP', 'opt_runtime', 'optimum_lnp_history', 'x', 'z']>
(85, 1, 49152)


In [15]:
data_box['lengthscales'] = [0.3, 200.0]
data_box['B'] = 2.0
data_box['j'] = np.arange(6, dtype=int)

with h5py.File('/data/asfe2/Projects/testselectionfunctions/cog_vi/ruwe1p4_mag_cogvi.h5', 'w') as hf:
    for key in data_box.keys():
        hf.create_dataset(key, data=data_box[key])